title: JH's page
url: "https://shlomo90.github.io"
baseurl: ""
image_baseurl: /images

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

disqus:
    shortname: shlomolim90

sass:
    style: compressed
    sass_dir: _sass

google_analytics: 'UA-170482767-1'

footer: yes
footer_url: "https://github.com/shlomo90/shlomo90.github.io"
footer_text: "Page design by JaeHwan Lim"

nav:
 - name: "Study"
   link: "study"
 - name: "Code"
   link: "code"
 - name: "Finder"
   link: "finder"
