title: JH Home
url: "https://shlomo90.github.io"
baseurl: ""

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

disqus:
    shortname: shlomolim90

sass:
    style: compressed
    sass_dir: _sass

footer: yes
footer_url: "https://github.com/shlomo90/shlomo90.github.io"
footer_text: "Page design by JaeHwan Lim"

nav:
 - name: "Study"
   link: "study"
 - name: "Todo"
   link: "todo"
 - name: "Contact"
   link: "contact"
